
image: ubuntu:22.04

stages:
  - build

variables:
  GO_VERSION: "1.24"

build:
  stage: build
  image: golang:${GO_VERSION}

  before_script:
    - id
    - cat /proc/self/status|grep Cap
    - apt-get update
    - apt-get install -y
      clang
      llvm
      libbpf-dev
      linux-libc-dev
      bpftool
      make
      git
      iproute2

  script:
    - bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
    - go mod download
    - go generate ./...
    - go build -v -o exec-tracer .

  script:
    - go mod download github.com/cilium/ebpf
    - go get github.com/cilium/ebpf/internal/unix@v0.19.0
    - make
    - ./exec-tracer >exec.log & 
    - ip addr
    - cat /etc/passwd
    - ls -la exec.log
    - cat exec.log
