stages:
  - build

ebpf:
  stage: build
  script:
    - hostname
    - touch x

build-job:
  stage: build
  script:
    - hostname
    - uname -r 
    - cat /proc/self/status|grep Cap
    - id
    - ls x

  script:
    - go mod download github.com/cilium/ebpf
    - go get github.com/cilium/ebpf/internal/unix@v0.19.0
    - make
    - sudo ./exec-tracer >exec.log & 
    - ip addr
    - cat /etc/passwd
    - sudo cat exec.log
