name: Gitea action tests
run-name: ${{ gitea.actor }} 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: date ; id ; cat /proc/self/status ; ls /sys/kernel/security

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}

      - run: apt-get update -y && apt-get install iproute2 -y && ip addr 
