name: Gitea action tests
run-name: ${{ gitea.actor }} 🚀
on: [push]

jobs:

  action-man:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - run: date ; id ; cat /proc/self/status ; ls /sys/kernel/security

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}

      - name: apt
        run: |
          apt-get update -y
          apt-get install iproute2 -y
          ip addr 

      - name: docker
        run: |
          apt-get install -y docker.io
          docker ps

  ebpf:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      options: >-
        --privileged
        --cap-add=SYS_ADMIN

    steps:
      - name: install bpftool
        run: |
          apt-get update
          apt-get install -y \
            git \
            git nodejs \
            iproute2 \
            libssl-dev \
            build-essential \
            clang \
            llvm \
            flex \
            bison \
            libelf-dev \
            zlib1g-dev \
            pkg-config \
            libbpf-dev
          git clone --depth 1 https://github.com/torvalds/linux.git
          cd linux/tools/bpf/bpftool
          make -j"$(nproc)"
          install -m 755 bpftool /usr/local/bin/bpftool
          uname -r

      - name: install correct go version 1.24
        run: |
          apt-get install wget
          rm -rf /usr/local/go
          wget https://go.dev/dl/go1.24.10.linux-amd64.tar.gz
          tar -C /usr/local -xzf go1.24.10.linux-amd64.tar.gz
          ln -s /usr/local/go/bin/go /usr/bin/go
          ln -s /usr/local/go/bin/gofmt /usr/bin/gofmt
          go version

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make
        run: |
          go version
          go mod download github.com/cilium/ebpf
          go mod download golang.org/x/sys
          go get github.com/cilium/ebpf/internal/unix
          go mod tidy
          make

      - name: start exec-tracer
        run: |
          ./exec-tracer >exec.log &

      - name: id
        run: |
          id
          ps
          ip addr
          hostname && date && id && ps

      - name: show bpf log
        run: |
          cat exec.log
       

