name: Gitea action tests
run-name: ${{ gitea.actor }} 🚀
on: [push]

jobs:

  action-man:
    runs-on: ubuntu-latest
    steps:
      - run: date ; id ; cat /proc/self/status ; ls /sys/kernel/security

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ gitea.workspace }}

      - name: apt
        run: |
          apt-get update -y
          apt-get install iproute2 -y
          ip addr 

      - name: docker
        run: |
          apt-get install -y docker.io
          docker ps

  ebpf:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            llvm \
            flex \
            bison \
            libelf-dev \
            zlib1g-dev \
            pkg-config \
            libbpf-dev
          git clone --depth 1 https://github.com/torvalds/linux.git
          cd linux/tools/bpf/bpftool
          make -j"$(nproc)"
          sudo install -m 755 bpftool /usr/local/bin/bpftool
          uname -r

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make
        run: |
          go mod download github.com/cilium/ebpf
          go get github.com/cilium/ebpf/internal/unix@v0.19.0
          make

      - name: start exec-tracer
        run: |
          sudo ./exec-tracer >exec.log &

      - name: id
        run: |
          hostname && date && id && ps && ip addr
          cat exec.log
       

