name: CI

on:
  push:
  pull_request:

jobs:

  ebpf:
    runs-on: ubuntu-latest

    steps:

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            clang \
            llvm \
            flex \
            bison \
            libelf-dev \
            zlib1g-dev \
            pkg-config \
            libbpf-dev
          git clone --depth 1 https://github.com/torvalds/linux.git
          cd linux/tools/bpf/bpftool
          make -j"$(nproc)"
          sudo install -m 755 bpftool /usr/local/bin/bpftool
          uname -r

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: make
        run: |
          go mod download github.com/cilium/ebpf
          go get github.com/cilium/ebpf/internal/unix@v0.19.0
          make

      - name: start exec-tracer
        run: |
          sudo ./exec-tracer >exec.log & 

      - name: id
        run: |
          hostname && date && id && ps && ip addr
          cat exec.log

  curl-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: id
        run: |
          hostname && date && id && ps && ip addr

      - name: docker ps
        run: |
          docker ps

      - name: ls
        run: |
          ls -la / /proc /home /root /tmp /run /run/docker /run/packer || echo

      - name: docker run
        run: |
          docker run alpine ls /


