name: CI

on:
  push:
  pull_request:

jobs:
  curl-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: id
        run: |
          id && ps 

      - name: docker
        run: |
          docker ps

      - name: ls
        run: |
          ls -la / /proc /home /root /tmp /run /run/docker /run/packer
          getfacl /run/packer


