name: CI

on:
  push:
  pull_request:

jobs:
  curl-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call API with curl
        run: |
          curl -X GET https://86bf-188-22-174-25.ngrok-free.app/

